### ISSUE TITLE
Add checks for NCEI archiving compliance

### ISSUE THREAD

**Issue by Bobfrat** [ioos/cc-plugin-glider#25]
I think we'll need Tom Ryans latest tables so we can check metadata attributes against this table. 

@benjwadams @kerfoot can you help us define the checks that we'll need based on the recent conversations?

1) Check institution attribute against table
2) Check project attribute against table (looks like Tom can add to these tables so this might not be a failure, just a warning)
3) Check for consistent use of filename and global attributes (id, title, source, summary)
4) Check platform_type against table (this may already be in there)

**Comment by benjwadams** [comment]
Implemented by #27, closing.
