### ISSUE TITLE
Rename the default branch to main

### ISSUE THREAD

**Issue by ocefpaf** [ioos/cc-plugin-glider#41]
@MathewBiddle do you have admin rights here to make this change for us?

@benjwadams any objections to renaming the development branch to `main`?

**Comment by MathewBiddle** [comment]
@ocefpaf I do. Just let me know when to make the change.

**Comment by ocefpaf** [comment]
IMO, we can do it now.

**Comment by MathewBiddle** [comment]
done. If you have this repo locally, you need to take the following actions:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
