### ISSUE TITLE
Documentation reference

### ISSUE THREAD

**Issue by jcermauwedu** [ioos/cc-plugin-glider#49]
When running the plugin, the documentation reference displayed takes the user into archived content.
```
--------------------------------------------------------------------------------
                         IOOS Compliance Checker Report                         
                    Version 5.0.3.dev252+g303d136.d20240315                     
                     Report generated 2024-03-15T05:52:47Z                      
                                 gliderdac:3.0                                  
   https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2    
--------------------------------------------------------------------------------
```

This should be `https://ioos.github.io/glider-dac/ngdac-netcdf-file-format-version-2`?

I will be submitting a PR in the near future, I can include this update if helpful.

**Comment by ocefpaf** [comment]
> I will be submitting a PR in the near future, I can include this update if helpful.

Yes, please! We moved that documentation recently and missed a few places when updating.
